# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubWindow(object):
    def setupUi(self, SubWindow):
        SubWindow.setObjectName("SubWindow")
        SubWindow.resize(688, 634)
        self.textBrowser = QtWidgets.QTextBrowser(SubWindow)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 671, 621))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(SubWindow)
        QtCore.QMetaObject.connectSlotsByName(SubWindow)

    def retranslateUi(self, SubWindow):
        _translate = QtCore.QCoreApplication.translate
        SubWindow.setWindowTitle(_translate("SubWindow", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubWindow = QtWidgets.QWidget()
    ui = Ui_SubWindow()
    ui.setupUi(SubWindow)
    SubWindow.show()
    sys.exit(app.exec_())
